---
- name: Ensure borg is installed
  package:
    name: "{{ borg.package_name }}"

- name: Push borg gathering fact on client
  copy:
    src: borg.fact
    dest: /etc/ansible/facts.d/
    mode: 0500
    owner: root
  register: borg_gathering_fact

- name: reload ansible_local
  setup: filter=ansible_local
  when: borg_gathering_fact.changed
...
