---
- action: borg_validate

- action: borg_init

- import_tasks: common.yml
  when: borg.server.clients != [] or borg_server is defined

- import_tasks: server.yml
  when: borg.server.clients != []

- import_tasks: client.yml
  when: borg_server is defined
...
